version: '3'
services:
  app:
    image: node:8.9.3
    volumes:
      - $PWD:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8000:8000
    command: npm run develop
    environment:
      NODE_ENV: ${NODE_ENV:-dev}

volumes:
  libs:

