version: "3.7"
services:
  nginx:
    image: nginx:1.13.12-alpine
    volumes:
      - ./.docker/start-nginx.sh:/usr/bin/start-nginx.sh
      - ./nginx:/etc/nginx-conf
      - ./public:/var/www/html
      - certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      SERVER_NAME: ${SERVER_NAME}
    command: start-nginx.sh
    depends_on:
    - gpo
  certbot:
    image: certbot/certbot:v1.2.0
    volumes:
      - ./.docker/sleep-certbot.sh:/usr/bin/sleep-certbot.sh
      - ./public:/var/www/html
      - certs:/etc/letsencrypt
    entrypoint: sleep-certbot.sh
  gpo:
    build: ./gpo/
    depends_on:
    - gpodb
    - gporedis
    command: gunicorn mygpo.wsgi --bind=0.0.0.0:8000 --timeout 600 --workers 3
    environment:
      CELERY_BROKER_URL: redis://gporedis:6379//
      DATABASE_URL: postgres://mygpo:mygpo@gpodb/mygpo
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      SECRET_KEY: ${GPO_SECRET_KEY:?}
  gpodb:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: mygpo
      POSTGRES_PASSWORD: mygpo
      POSTGRES_USER: mygpo
    volumes:
    - gpodb:/var/lib/postgresql/data
  gporedis:
    image: redis:6.0.10-alpine
    restart: always

volumes:
  certs:
  gpodb:
