module.exports = {
  plugins: [
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'data',
        path: `${__dirname}/data/`,
      },
    },
    {
      resolve: 'gatsby-source-goodreads',
      options: { userId: 21996113 },
    },
    {
      resolve: 'gatsby-source-podcasts',
      options: {
        rsses: [
          'https://www.scientificamerican.com/sciam/xml/iTunes.cfm?id=60-second-science',
          'http://wesa.fm/podcasts/13403/rss.xml',
          'http://feeds.99percentinvisible.org/99percentinvisible',
          'https://chariotsolutions.com/podcasts/show/all-shows/feed/',
          'http://feeds.soundcloud.com/users/soundcloud:users:213324253/sounds.rss',
          'http://arsparadoxica.libsyn.com/rss',
          'http://audiobliviousproductions.libsyn.com/rss',
          'http://campfireradiotheater.podbean.com/feed/',
          'http://feeds.feedburner.com/clarkesworldmagazine/podcast',
          'https://audioboom.com/channels/4901846.rss',
          'http://feeds.gimletmedia.com/crimetownshow',
          'http://feeds.thisiscriminal.com/CriminalShow',
          'http://criminalinjustice.libsyn.com/rss',
          'http://feeds.feedburner.com/dancarlin/history?format=xml',
          'http://darkestnight.libsyn.com/rss',
          'http://dataskeptic.libsyn.com/rss',
          'http://feeds.feedburner.com/DrupalEasyPodcast',
          'http://escapepod.org/feed/',
          'https://wesa.drupal.publicbroadcasting.net/podcasts/term/10528/rss.xml',
          'http://unwantedchildren.libsyn.com/rss',
          'http://api.spokenlayer.com/feed/channel/v1-intercept-news2-ext/3c9929b72538c12bd92ac6762f8d798b9d4e8cdca7692ea74f466061d01816cb',
          'http://www.espn.com/espnradio/podcast/feeds/itunes/podCast?id=14554755',
          'https://feeds.megaphone.fm/PPY8359579005',
          'http://feeds.twit.tv/floss.xml',
          'http://feeds.feedburner.com/freakonomicsradio',
          'https://www.gamerswithjobs.com/podcast/gwjcc/feed',
          'http://feeds.feedburner.com/grapplepodcast',
          'https://feeds.megaphone.fm/ADL4668203624',
          'https://feeds.podcastmirror.com/historium',
          'http://feeds.gimletmedia.com/homecomingshow',
          'http://feeds.feedburner.com/onarchitecture',
          'http://feeds.feedburner.com/IQ2USDebates',
          'http://feeds.feedburner.com/InterceptedWithJeremyScahill',
          'https://www.npr.org/rss/podcast.php?id=510307',
          'https://krpoliticaljunkie.com/feed/podcast',
          'http://letsnotmeet.libsyn.com/rss',
          'http://feeds.feedburner.com/themessagepodcast',
          'http://feeds.megaphone.fm/PPY5621646923',
          'http://feeds.feedburner.com/udacity-linear-digressions?format=xml',
          'http://lorepodcast.libsyn.com/rss',
          'https://www.blubrry.com/feeds/mythospodcast.xml',
          'http://feeds.podtrac.com/2P68PDQSg03Y',
          'http://feeds.feedburner.com/OhNoPodcast',
          'http://ostium.libsyn.com/rss',
          'http://feeds.feedburner.com/NCSL_OAS',
          'http://ourfakehistory.libsyn.com/rss',
          'http://feeds.feedburner.com/PartiallyDerivative',
          'https://www.npr.org/rss/podcast.php?id=510289',
          'http://pleasingterrors.libsyn.com/rss',
          'http://feeds.feedburner.com/pod-save-the-world',
          'http://pointmystic.libsyn.com/rss',
          'https://www.mprnews.org/podcasts/political-junkie',
          'http://pseudopod.org/feed/',
          'http://rabbits.libsyn.com/rss',
          'http://feeds.wnyc.org/moreperfect',
          'http://www.returnhomepodcast.com/podcast/podcast.xml',
          'http://feeds.revealradio.org/revealpodcast',
          'http://feeds.feedburner.com/RevisionistHistory',
          'http://feeds.stownpodcast.org/stownpodcast',
          'http://sawbones.libsyn.com/rss',
          'http://nojargon.libsyn.com/rss',
          'http://feeds.gimletmedia.com/sciencevs',
          'http://feeds.twit.tv/sn',
          'http://feeds.serialpodcast.org/serialpodcast',
          'http://feeds.nightvalepresents.com/sleepwithme',
          'http://smalltownhorror.libsyn.com/rss',
          'http://feeds.feedburner.com/se-radio',
          'http://rss.acast.com/starshipsofa',
          'https://feeds.megaphone.fm/stuffyoumissedinhistoryclass',
          'http://found.libsyn.com/rss',
          'https://feeds.megaphone.fm/ADL4453598034',
          'http://www.supremepodcast.com/SupremePodcast.com/A_Weekly_Podcast_Concerning_the_United_States_Supreme_Court/rss.xml',
          'http://rss.acast.com/talestoterrify',
          'http://tanis.libsyn.com/rss',
          'https://kuow.drupal.publicbroadcasting.net/podcasts/102329/rss.xml',
          'http://feeds.feedburner.com/alleghenyfront',
          'http://theblacktapes.libsyn.com/rss',
          'http://feeds.propublica.org/propublica/podcast',
          'http://thebrightsessions.libsyn.com/rss',
          'https://wesa.drupal.publicbroadcasting.net/podcasts/70488/rss.xml',
          'https://audioboom.com/channels/4852902.rss',
          'http://www.drabblecast.org/feed/podcast-m4a/',
          'https://www.thefarmeridian.com/feed?format=rss',
          'http://feedpress.me/victoriaslift',
          'http://rss.acast.com/themagnusarchives',
          'http://feeds.thememorypalace.us/thememorypalace',
          'http://feeds.feedburner.com/themothpodcast',
          'https://rss.art19.com/nosleep',
          'http://rss.acast.com/theotherstories',
          'http://maddmike.libsyn.com/rss',
          'https://audioboom.com/channels/4956043.rss',
          'https://feed.theskepticsguide.org/feed/rss.aspx?feed=5x5',
          'https://feed.theskepticsguide.org/feed/rss.aspx?feed=sgu',
          'https://thestrangeandunusualpodcast.libsyn.com/rss',
          'http://thewayiheardit.rsvmedia.com/rss/',
          'http://thewickedlibrary.com/feed/podcast',
          'http://thescalawags.libsyn.com/rss',
          'https://rss.art19.com/thinking-sideways',
          'http://feed.thisamericanlife.org/talpodcast',
          'http://feeds.feedburner.com/thisdeveloperslife',
          'http://trumponearth.libsyn.com/rss',
          'https://audioboom.com/channels/4741997.rss',
          'http://feeds.wvpublic.org/usthempodcast',
          'https://www.npr.org/rss/podcast.php?id=344098539',
          'http://feeds.TrumpConLaw.com/TrumpConLaw',
          'http://feeds.feedburner.com/with-friends-like-these',
          'http://wolf359radio.libsyn.com/rss',
        ],
      },
    },
    'gatsby-transformer-remark',
    'gatsby-transformer-yaml',
    'gatsby-remark-autolink-headers',
    'gatsby-plugin-catch-links',
    'gatsby-plugin-glamor',
    'gatsby-plugin-lodash',
    'gatsby-plugin-nprogress',
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: 'UA-87597611-1',
      },
    },
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-typography',
      options: {
        pathToConfigModule: 'src/styles.js',
      },
    },
  ],
  siteMetadata: {
    siteUrl: 'http://cmlubinski.info',
  },
};
